# Generated by Django 5.1.3 on 2024-11-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TimeField(max_length=50, null=True)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField(max_length=400, null=True)),
            ],
        ),
    ]
