# Generated by Django 5.1.3 on 2024-11-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Name',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
