# Generated by Django 5.1.3 on 2024-11-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0003_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Time',
            field=models.TimeField(),
        ),
    ]
