# Generated by Django 5.1.3 on 2024-11-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0004_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Time',
            field=models.DateTimeField(),
        ),
    ]
