# Generated by Django 5.1.3 on 2024-11-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0005_alter_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique identifier for the event, such as a short name or code.', max_length=100)),
                ('title', models.CharField(help_text='Full title of the event.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event.')),
                ('image', models.ImageField(blank=True, help_text='An image representing the event.', null=True, upload_to='event_images/')),
                ('date', models.DateTimeField(help_text='Date and time when the event is scheduled to take place.')),
                ('location', models.CharField(help_text='Venue or location where the event will take place.', max_length=255)),
                ('organizer', models.CharField(help_text='The person or organization hosting the event.', max_length=100)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email for event inquiries.', max_length=254, null=True)),
                ('is_virtual', models.BooleanField(default=False, help_text='Indicates if the event is virtual or in-person.')),
                ('registration_link', models.URLField(blank=True, help_text='Link for participants to register for the event.', null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
